FROM node:22-bookworm-slim AS build

WORKDIR /app

COPY ./src/client/package*.json ./
RUN npm ci
RUN npm install --no-save less

COPY ./src/client/ ./
RUN find ./src ./public -name '*.less' -print0 | xargs -0 -I{} sh -c 'npx lessc -x --strict-imports "$1" "${1%.less}.css"' -- {}
RUN npm run build

FROM nginx:alpine

RUN apk add --no-cache netcat-openbsd

COPY ./src/client/nginx.isleward.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/ /usr/share/nginx/html/

EXPOSE 80
