/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export namespace physics {
  export interface Physics {
    graph: ExternalObject<PhysicsGraph>
    collisionMap: Array<Array<boolean>>
    cells: Array<Array<Array<PhysicsObject>>>
    width: number
    height: number
  }
  export interface PhysicsObject {
    x: number
    y: number
    width: number
    height: number
    id: string
  }
  export interface Coordinate {
    x: number
    y: number
  }
}
