/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export namespace physics {
  export interface Physics {
    graph: ExternalObject<Graph>
    collisionMap: Array<Array<boolean>>
    cells: Array<Array<Array<number>>>
    width: number
    height: number
  }
}
